import { beforeEach, describe, expect, it, vi } from 'vitest';
import { createMonster, gainExperience, maxHp, SPECIES } from './content';
import { BATTLE_FINISH_SECONDS, BATTLE_RECALL_END_SECONDS, CAPTURE_FAIL_SECONDS, CAPTURE_FINISH_SECONDS, CAPTURE_RECALL_END_SECONDS, Game } from './game';
import { canPlayerOccupy, collidesWithArt, collidesWithNpcAt, collidesWithNpcs } from './assetCollision';
import { ART_FOOTPRINTS, ART_FOOTPRINT_AREAS, CHARACTER_FOOTPRINTS } from './generatedFootprints';
import { tileAt } from './world';

const store=new Map<string,string>();
beforeEach(()=>{
  store.clear();
  vi.stubGlobal('localStorage',{getItem:(key:string)=>store.get(key)||null,setItem:(key:string,value:string)=>store.set(key,value)});
  vi.restoreAllMocks();
});

describe('progressão e captura',()=>{
  it('abre o empório na porta e compra para o inventário e a coleção de cartas',()=>{
    const game=new Game();game.newGame('brasito',40732);
    game.wildActors=[];game.walkingNpcs=[];
    game.player.x=57.5;game.player.z=57.5;
    expect(game.nearbyInteraction()?.kind).toBe('shop');
    game.interact();
    expect(game.shopOpen).toBe(true);
    const before=game.save!.inventory.length;
    const initialCards=game.save!.cards.fogo;
    const initialCoins=game.save!.coins;
    expect(game.buyFromShop('pao',2)).toBe(true);
    expect(game.save!.inventory.length).toBe(before+2);
    expect(game.save!.inventory.at(-1)?.uid).not.toBe(game.save!.inventory.at(-2)?.uid);
    expect(game.save!.coins).toBe(initialCoins-36);
    expect(game.buyFromShop('carta-fogo',1)).toBe(true);
    expect(game.save!.cards.fogo).toBe(initialCards+1);
    expect(game.buyFromShop('bolo',20)).toBe(false);
    expect(game.buyFromShop('pao',0)).toBe(false);
    game.closeShop();
    expect(game.buyFromShop('pao',1)).toBe(false);
    const resumed=new Game();expect(resumed.continueGame()).toBe(true);
    expect(resumed.save!.coins).toBe(game.save!.coins);
    expect(resumed.save!.cards.fogo).toBe(initialCards+1);
    expect(resumed.save!.inventory.length).toBe(before+2);
  });
  it('concede moedas aos jogos antigos sem apagar sua coleção',()=>{
    const original=new Game();original.newGame('gotejo',40732);
    const stored=JSON.parse(store.get('cartas-e-monstros-save-v1')!);
    delete stored.coins;delete stored.nextShopSerial;
    store.set('cartas-e-monstros-save-v1',JSON.stringify(stored));
    const resumed=new Game();expect(resumed.continueGame()).toBe(true);
    expect(resumed.save!.coins).toBe(120);
    expect(resumed.save!.party[0].species).toBe('gotejo');
  });
  it('salta um nível, aterrissa e desce um degrau sem precisar de rampa',()=>{
    const game=new Game();game.newGame('brasito',40732);
    const world=game.world!;
    const pair=world.tiles.flatMap(tile=>[[1,0],[-1,0],[0,1],[0,-1]].map(([dx,dz])=>{
      const from={x:tile.x+0.5,z:tile.z+0.5};
      const to={x:tile.x+dx+0.5,z:tile.z+dz+0.5};
      const next=tileAt(world,tile.x+dx,tile.z+dz);
      return {tile,next,from,to,dx,dz};
    })).find(item=>item.next?.height===item.tile.height+1&&item.tile.terrain!=='ramp'&&item.next.terrain!=='ramp'&&
      canPlayerOccupy(world,item.from,item.from)&&canPlayerOccupy(world,item.from,item.to,true)&&
      !canPlayerOccupy(world,item.from,item.to));
    expect(pair).toBeDefined();
    game.wildActors=[];
    game.player.x=pair!.from.x;game.player.z=pair!.from.z;
    game.setMove(pair!.dx,pair!.dz);
    expect(game.jumpForward()).toBe(true);
    expect(game.jump).not.toBeNull();
    for(let i=0;i<12;i++)game.update(0.05);
    expect(game.jump).toBeNull();
    expect(game.jumpLandingTime).toBe(0.18);
    expect(game.jumpForward()).toBe(false);
    expect(game.player).toEqual(pair!.to);
    expect(game.getGroundHeight(game.player.x,game.player.z)).toBeGreaterThan(pair!.tile.height*0.85);
    game.setMove(-pair!.dx,-pair!.dz);
    for(let i=0;i<7;i++)game.update(0.05);
    expect(game.getGroundHeight(game.player.x,game.player.z)).toBe(pair!.tile.height*0.85);
  });
  it('permite ao herói pular na batalha e pausa o salto enquanto escolhe um item',()=>{
    const game=new Game();game.newGame('brasito',40732);
    game.beginBattle(game.wildActors[0]);
    expect(game.jumpForward()).toBe(false);
    game.battle!.intro=0;
    game.battle!.ally.attackTimer=999;game.battle!.foe.attackTimer=999;
    game.setMove(0,0);
    const start={...game.player};
    expect(game.jumpForward()).toBe(true);
    for(let i=0;i<5;i++)game.update(0.05);
    expect(game.playerVisualLift).toBeGreaterThan(0.5);
    expect(game.player).toEqual(start);
    game.openBattleMenu('items');
    const elapsed=game.jump!.elapsed;
    expect(game.jumpForward()).toBe(false);
    for(let i=0;i<10;i++)game.update(0.05);
    expect(game.jump!.elapsed).toBe(elapsed);
    game.closeBattleMenu();
    for(let i=0;i<12;i++)game.update(0.05);
    expect(game.jump).toBeNull();
    expect(game.playerVisualLift).toBe(0);
    expect(game.battle!.ally.dodgeCooldown).toBe(0);
  });
  it('só eleva o herói depois que o quadro do salto sai do chão',()=>{
    const game=new Game();game.newGame('brasito',40732);
    game.wildActors=[];
    game.setMove(1,0);
    expect(game.jumpForward()).toBe(true);
    game.update(0.05);
    expect(game.playerVisualLift).toBe(0);
    game.update(0.05);
    expect(game.playerVisualLift).toBeGreaterThan(0);
    for(let step=0;step<3;step++)game.update(0.05);
    expect(game.playerVisualLift).toBeGreaterThan(0.5);
  });
  it('faz a coleta e o uso manual de item ativarem gestos breves',()=>{
    const game=new Game();game.newGame('brasito',40732);
    const wild=game.wildActors[0];
    game.wildActors=[];game.walkingNpcs=[];
    const spawn=game.world!.items[0];
    game.player.x=spawn.x;game.player.z=spawn.z;
    const inventoryBefore=game.save!.inventory.length;
    game.interact();
    expect(game.save!.inventory).toHaveLength(inventoryBefore+1);
    expect(game.playerPickupTime).toBe(0.6);
    game.update(0.05);
    expect(game.playerPickupTime).toBeCloseTo(0.55);
    game.beginBattle(wild);
    game.battle!.intro=0;
    game.battle!.ally.hp=1;
    game.battle!.ally.attackTimer=999;game.battle!.foe.attackTimer=999;
    game.openBattleMenu('items');
    expect(game.useBattleItem('starter-pao')).toBe(true);
    expect(game.battle!.itemUseTime).toBe(0.38);
    expect(game.battle!.pendingItemThrow?.itemId).toBe('pao');
    expect(game.effects.some(effect=>effect.kind==='item'&&effect.itemId==='pao')).toBe(false);
    for(let step=0;step<3;step++)game.update(0.05);
    expect(game.battle!.pendingItemThrow?.itemId).toBe('pao');
    game.update(0.05);
    expect(game.battle!.pendingItemThrow).toBeNull();
    expect(game.effects.find(effect=>effect.kind==='item'&&effect.itemId==='pao'))
      .toMatchObject({x:game.player.x,z:game.player.z});
    expect(game.battle!.cue?.poseRemaining).toBe(0);
  });
  it('usa o gesto de coleta também ao pegar uma carta no mapa',()=>{
    const game=new Game();game.newGame('brasito',40732);
    game.wildActors=[];game.walkingNpcs=[];
    const cache=game.world!.caches[0];
    game.player.x=cache.x;game.player.z=cache.z;
    game.setMove(1,0);
    const cardsBefore=game.save!.cards[cache.element];
    expect(game.nearbyInteraction()?.kind).toBe('cache');
    game.interact();
    expect(game.save!.openedCaches).toContain(cache.id);
    expect(game.save!.cards[cache.element]).toBe(cardsBefore+1);
    expect(game.playerPickupTime).toBe(0.6);
    expect(game.move).toEqual({x:0,z:0});
    game.update(0.05);
    expect(game.playerPickupTime).toBeCloseTo(0.55);
  });
  it('mostra a derrota antes de resgatar a equipe e bloqueia comandos durante a animação',()=>{
    const game=new Game();game.newGame('brasito',40732);
    game.beginBattle(game.wildActors[0]);
    const battle=game.battle!;
    battle.intro=0;
    battle.ally.hp=0;
    battle.ally.attackTimer=999;
    battle.foe.attackTimer=999;
    game.update(0.05);
    expect(battle.defeat).toEqual({elapsed:0,duration:1});
    expect(game.mode).toBe('battle');
    game.battleCommand('attack');
    game.openBattleMenu('cards');
    game.togglePause();
    expect(battle.command).toBe('return');
    expect(game.battleMenu).toBeNull();
    expect(game.mode).toBe('battle');
    for(let step=0;step<20;step++)game.update(0.05);
    expect(game.battle).toBeNull();
    expect(game.mode).toBe('explore');
    expect(game.player).toEqual({x:48,z:48});
  });
  it('usa a base opaca das casas para bloquear apenas onde a arte ocupa espaço',()=>{
    const game=new Game();game.newGame('brasito',40732);
    const world=game.world!;
    const house=world.places.find(place=>place.kind==='house')!;
    const center={x:house.x+0.5,z:house.z+0.5};
    expect(canPlayerOccupy(world,center,center)).toBe(false);
    const oldBlocked=world.tiles.filter(tile=>tile.blocked&&Math.abs(tile.x-house.x)<=1&&Math.abs(tile.z-house.z)<=1);
    expect(oldBlocked.some(tile=>{
      const point={x:tile.x+0.5,z:tile.z+0.5};
      return canPlayerOccupy(world,point,point);
    })).toBe(true);
  });
  it('bloqueia o corpo desenhado da casa e deixa a frente da porta livre',()=>{
    const game=new Game();game.newGame('brasito',40732);
    const world=game.world!;
    const house=world.places.find(place=>place.id==='casa-cartas')!;
    const center={x:house.x+0.5,z:house.z+0.5};
    expect(ART_FOOTPRINT_AREAS[house.id].rows).toHaveLength(20);
    expect(collidesWithArt(world,{x:center.x-1,z:center.z-1})).toBe(true);
    expect(collidesWithArt(world,{x:center.x+1,z:center.z+1})).toBe(false);
  });
  it('permite chegar até a porta do ateliê sem atravessar a casa',()=>{
    const game=new Game();game.newGame('brasito',40732);
    game.wildActors=[];game.walkingNpcs=[];
    game.player.x=44.5;game.player.z=49.5;
    game.setMove(0,-1);
    for(let step=0;step<30;step++)game.update(0.05);
    expect(game.player.z).toBeGreaterThan(46.5);
    expect(game.player.z).toBeLessThan(48);
    game.setMove(0,0);game.interact();
    expect(game.dialog?.title).toBe('Ateliê de Cartas');
  });
  it('usa o tronco da árvore e os pés dos NPCs como área de colisão',()=>{
    const game=new Game();game.newGame('brasito',40732);
    const world=game.world!;
    expect(ART_FOOTPRINTS.tree.split('1').length-1).toBeLessThan(20);
    expect(CHARACTER_FOOTPRINTS.cartographer).toContain('1');
    const tree=world.tiles.find(tile=>tile.prop==='tree')!;
    const trunk={x:tree.x+0.5,z:tree.z+0.5};
    expect(canPlayerOccupy(world,trunk,trunk)).toBe(false);
    const npc=game.walkingNpcs[0];
    const npcPoint={x:npc.x,z:npc.z};
    expect(collidesWithNpcAt(npcPoint,npc)).toBe(true);
    expect(collidesWithNpcs(world,npcPoint,game.walkingNpcs)).toBe(true);
    expect(collidesWithNpcAt({x:npc.x+1.5,z:npc.z-1.5},npc)).toBe(false);
  });
  it('impede que os pés avancem sobre a água mesmo antes do centro mudar de tile',()=>{
    const game=new Game();game.newGame('brasito',40732);
    const world=game.world!;
    const shore=world.tiles.flatMap(tile=>[[1,0],[-1,0],[0,1],[0,-1]].map(([dx,dz])=>({tile,dx,dz})))
      .find(({tile,dx,dz})=>tile.terrain!=='water'&&tileAt(world,tile.x+dx,tile.z+dz)?.terrain==='water'&&
        canPlayerOccupy(world,{x:tile.x+0.5,z:tile.z+0.5},{x:tile.x+0.5,z:tile.z+0.5})&&
        !collidesWithArt(world,{x:tile.x+0.91*dx+(dx===0?0.5:dx>0?0:1),z:tile.z+0.91*dz+(dz===0?0.5:dz>0?0:1)}));
    expect(shore).toBeDefined();
    const {tile,dx,dz}=shore!;
    const from={x:tile.x+0.5,z:tile.z+0.5};
    const nearEdge={x:from.x+dx*0.41,z:from.z+dz*0.41};
    expect(Math.floor(nearEdge.x)).toBe(tile.x);
    expect(Math.floor(nearEdge.z)).toBe(tile.z);
    expect(canPlayerOccupy(world,from,nearEdge)).toBe(false);
  });
  it('mostra a invocação antes de liberar os comandos e ataques',()=>{
    const game=new Game();game.newGame('brasito',1234);
    const wild=game.wildActors.find(w=>!w.night)!;
    game.save!.player={x:wild.x-1,z:wild.z};
    game.beginBattle(wild);
    const battle=game.battle!;
    expect(Math.hypot(battle.ally.x-game.player.x,battle.ally.z-game.player.z)).toBeGreaterThan(0.75);
    expect(Math.hypot(battle.ally.x-game.player.x,battle.ally.z-game.player.z)).toBeLessThan(2.25);
    expect(battle.command).toBe('return');
    expect(game.message).toBe('');
    const hp=battle.foe.hp;
    game.battleCommand('follow');
    expect(battle.command).toBe('return');
    for(let i=0;i<20;i++)game.update(0.05);
    expect(battle.time).toBe(0);
    expect(battle.foe.hp).toBe(hp);
    for(let i=0;i<40;i++)game.update(0.05);
    expect(battle.intro).toBe(0);
    expect(battle.introSummoned).toBe(true);
    expect(battle.time).toBeGreaterThan(0);
  });
  it('moradores novos caminham em tiles livres, conversam e param na pausa',()=>{
    const game=new Game();game.newGame('gotejo',1234);
    expect(game.walkingNpcs).toHaveLength(4);
    const npc=game.walkingNpcs[0];
    game.player.x=npc.x;game.player.z=npc.z+1;
    vi.spyOn(Math,'random').mockReturnValue(0);
    const start=npc.x;
    for(let i=0;i<12;i++)game.update(0.05);
    expect(npc.x).toBeGreaterThan(start);
    game.togglePause();
    const paused=npc.x;
    for(let i=0;i<12;i++)game.update(0.05);
    expect(npc.x).toBe(paused);
    game.togglePause();
    game.interact();
    expect(game.dialog?.title).toContain('Nara');
  });
  it('mostra a ação próxima e mantém a conversa no mapa até interagir de novo',()=>{
    const game=new Game();game.newGame('brasito',1234);
    game.wildActors=[];
    const npc=game.walkingNpcs[0];
    game.player.x=npc.x;game.player.z=npc.z+1;
    expect(game.nearbyInteraction()).toMatchObject({kind:'walker',id:npc.id,verb:'Falar'});
    game.setMove(0,-1);
    game.interact();
    expect(game.mode).toBe('dialog');
    expect(game.dialog?.anchor).toEqual({x:npc.x,z:npc.z});
    expect(game.move).toEqual({x:0,z:0});
    const position={...game.player};
    game.setMove(1,0);game.update(0.05);
    expect(game.player).toEqual(position);
    game.interact();
    expect(game.mode).toBe('explore');
    expect(game.dialog).toBeNull();
    expect(game.move).toEqual({x:0,z:0});
  });
  it('usa o mesmo alvo contextual para abrir uma casa no mapa',()=>{
    const game=new Game();game.newGame('brasito',40732);
    game.wildActors=[];game.walkingNpcs=[];
    game.player.x=44.5;game.player.z=47.5;
    expect(game.nearbyInteraction()).toMatchObject({kind:'place',id:'casa-cartas',verb:'Interagir'});
    game.interact();
    expect(game.dialog?.anchor).toEqual({x:45.45,z:48.05});
    expect(game.dialog?.actions.some(action=>action.label.includes('Criar carta'))).toBe(true);
    expect(game.chooseDialogAction(9)).toBe(false);
    const cards=game.save!.cards.fogo;
    expect(game.chooseDialogAction(0)).toBe(true);
    expect(game.save!.cards.fogo).toBe(cards+1);
    expect(game.mode).toBe('explore');
  });
  it('evolui ao alcançar o nível 6',()=>{
    const monster=createMonster('brasito',5,'test');
    monster.hp=17;
    const outcome=gainExperience(monster,100);
    expect(outcome.evolved).toBe(true);
    expect(monster.species).toBe('brasalto');
    expect(monster.hp).toBe(17);
  });
  it('mantém a vida restante depois da vitória, do nível ganho e no encontro seguinte',()=>{
    const game=new Game();game.newGame('brasito',346);
    const wild=game.wildActors.find(w=>!w.night)!;
    game.beginBattle(wild);
    const battle=game.battle!;
    battle.intro=0;
    battle.ally.hp=13;
    battle.ally.x=battle.foe.x;
    battle.ally.z=battle.foe.z;
    battle.foe.hp=1;
    battle.foe.attackTimer=100;
    game.battleCommand('attack');
    for(let step=0;step<120&&game.mode==='battle';step++)game.update(0.05);
    expect(game.mode).toBe('explore');
    expect(game.save!.party[0].level).toBeGreaterThan(1);
    expect(game.save!.party[0].hp).toBe(13);
    const restored=new Game();expect(restored.continueGame()).toBe(true);
    expect(restored.save!.party[0].hp).toBe(13);
    restored.beginBattle(restored.wildActors.find(w=>w.id!==wild.id&&!w.night)!);
    expect(restored.battle!.ally.hp).toBe(13);
  });
  it('exige vida baixa e carta do mesmo elemento',()=>{
    const game=new Game();game.newGame('gotejo',1234);
    const wild=game.wildActors.find(w=>SPECIES[w.species].element==='fogo')!;
    game.beginBattle(wild);
    game.battle!.intro=0;
    expect(game.captureChance()).toBe(0);
    const original=game.save!.cards.fogo;
    game.capture();
    expect(game.save!.cards.fogo).toBe(original);
    game.battle!.foe.hp=Math.floor(maxHp(game.battle!.enemy)*0.25);
    game.openBattleMenu('cards');
    expect(game.selectedBattleCard).toBe('fogo');
    game.selectBattleCard('agua');
    game.useSelectedBattleCard();
    expect(game.save!.cards.fogo).toBe(original);
    game.selectBattleCard('fogo');
    vi.spyOn(Math,'random').mockReturnValue(0);
    game.useSelectedBattleCard();
    expect(game.save!.cards.fogo).toBe(original-1);
    expect(game.save!.party.length+game.save!.collection.length).toBe(2);
    expect(game.mode).toBe('battle');
    expect(game.battle?.captureSequence?.success).toBe(true);
    const player={...game.player};
    game.setMove(1,0);game.battleCommand('attack');game.flee();game.openBattleMenu('items');
    for(let step=0;step<Math.ceil(CAPTURE_RECALL_END_SECONDS/0.05);step++)game.update(0.05);
    expect(game.player).toEqual(player);
    expect(game.battle?.captureSequence).toBeDefined();
    expect(game.battleMenu).toBeNull();
    for(let step=0;step<Math.ceil(CAPTURE_FINISH_SECONDS/0.05)+2&&game.mode==='battle';step++)game.update(0.05);
    expect(game.mode).toBe('explore');
    const restored=new Game();expect(restored.continueGame()).toBe(true);
    expect(restored.save!.party.length+restored.save!.collection.length).toBe(2);
  });
  it('persiste equipe, cartas e semente',()=>{
    const game=new Game();game.newGame('brotelho',7821);
    game.save!.cards.natureza=7;game.persist();
    const restored=new Game();expect(restored.continueGame()).toBe(true);
    expect(restored.save!.seed).toBe(7821);
    expect(restored.save!.party[0].species).toBe('brotelho');
    expect(restored.save!.cards.natureza).toBe(7);
  });
  it('concede selo ao vencer um guardião',()=>{
    const game=new Game();game.newGame('brasito',999);
    const shrine=game.world!.places.find(p=>p.element==='natureza')!;
    game.beginBattle(undefined,'natureza',shrine);
    game.battle!.intro=0;
    const battle=game.battle!;
    battle.ally.x=battle.foe.x;battle.ally.z=battle.foe.z;
    battle.foe.hp=1;battle.ally.windup=0.001;
    battle.ally.strikeOrigin={x:battle.ally.x,z:battle.ally.z};battle.ally.strikeRadius=2;
    game.update(0.02);
    expect(battle.finisher).toBeDefined();
    for(let step=0;step<Math.ceil(BATTLE_FINISH_SECONDS/0.05)+2&&game.mode==='battle';step++)game.update(0.05);
    expect(game.save!.seals).toContain('natureza');
    expect(game.battle).toBeNull();
  });
  it('congela a vitória, mostra o XP e só encerra após a carta do aliado retornar',()=>{
    const game=new Game();game.newGame('brasito',346);
    const wild=game.wildActors.find(w=>!w.night)!;
    game.beginBattle(wild);game.battle!.intro=0;
    const battle=game.battle!;
    battle.ally.x=battle.foe.x;battle.ally.z=battle.foe.z;
    battle.foe.hp=1;battle.foe.attackTimer=0;
    battle.ally.windup=0.001;
    battle.ally.strikeOrigin={x:battle.ally.x,z:battle.ally.z};battle.ally.strikeRadius=2;
    const cards={...game.save!.cards};
    const collection=game.save!.collection.length;
    const initialXp=game.save!.party[0].xp;
    const initialCoins=game.save!.coins;
    game.update(0.02);
    expect(battle.finisher?.elapsed).toBe(0);
    expect(battle.finisher?.enemyElement).toBe(SPECIES[battle.enemy.species].element);
    expect(battle.finisher?.allyElement).toBe(SPECIES[game.save!.party[0].species].element);
    expect(battle.finisher?.enemyElement).not.toBe(battle.finisher?.allyElement);
    expect(battle.foe.hp).toBe(0);
    expect(game.mode).toBe('battle');
    expect(game.save!.wins).toBe(0);
    const player={...game.player};
    const ally={x:battle.ally.x,z:battle.ally.z,hp:battle.ally.hp};
    game.setMove(1,0);
    game.battleCommand('attack');game.orderMove(player);game.capture();game.flee();game.openBattleMenu('cards');
    expect(battle.command).toBe('return');
    expect(game.battleMenu).toBeNull();
    for(let step=0;step<25;step++)game.update(0.05);
    expect(game.player).toEqual(player);
    expect({x:battle.ally.x,z:battle.ally.z,hp:battle.ally.hp}).toEqual(ally);
    expect(game.effects.filter(effect=>effect.kind==='xp')).toHaveLength(1);
    expect(game.mode).toBe('battle');
    for(let step=0;step<Math.ceil((BATTLE_RECALL_END_SECONDS-1.25)/0.05);step++)game.update(0.05);
    expect(game.mode).toBe('battle');
    expect(battle.finisher!.elapsed).toBeGreaterThanOrEqual(BATTLE_RECALL_END_SECONDS);
    for(let step=0;step<Math.ceil(BATTLE_FINISH_SECONDS/0.05)+2&&game.mode==='battle';step++)game.update(0.05);
    expect(game.mode).toBe('explore');
    expect(game.save!.wins).toBe(1);
    expect(game.save!.coins).toBeGreaterThan(initialCoins);
    expect(game.save!.party[0].xp).toBeGreaterThan(initialXp);
    expect(game.save!.cards).toEqual(cards);
    expect(game.save!.party).toHaveLength(1);
    expect(game.save!.collection).toHaveLength(collection);
  });
  it('pausa a arena nos menus e executa comandos e ataques automáticos',()=>{
    const game=new Game();game.newGame('gotejo',321);
    const wild=game.wildActors.find(w=>!w.night)!;
    game.beginBattle(wild);
    game.battle!.intro=0;
    const battle=game.battle!;
    const time=battle.time;
    game.openBattleMenu('cards');
    game.update(0.05);
    expect(battle.time).toBe(time);
    game.battleCommand('return');
    expect(battle.command).toBe('return');
    game.closeBattleMenu();
    game.battleCommand('follow');
    expect(battle.command).toBe('follow');
    game.battleCommand('dodge');
    expect(battle.ally.dodgeTime).toBeGreaterThan(0);
    game.battleCommand('dodge');
    expect(battle.ally.dodgeCooldown).toBeGreaterThan(0);
    const waypoint={x:battle.center.x+0.5,z:battle.center.z+0.5};
    game.orderMove(waypoint);
    expect(battle.command).toBe('move');
    expect(battle.waypoint).toEqual(waypoint);
    game.battleCommand('attack');
    battle.ally.x=battle.foe.x;battle.ally.z=battle.foe.z;
    battle.ally.attackTimer=0;battle.foe.attackTimer=5;
    const foeHp=battle.foe.hp;
    for(let step=0;step<16;step++)game.update(0.05);
    expect(battle.time).toBeGreaterThan(time);
    expect(battle.foe.hp).toBeLessThan(foeHp);
    expect(game.effects.some(effect=>effect.kind==='damage'&&effect.amount!>0)).toBe(true);
  });
  it('avisa antes da habilidade inimiga e permite esquivar do golpe',()=>{
    const game=new Game();game.newGame('brasito',346);
    game.beginBattle(game.wildActors.find(w=>!w.night)!);
    game.battle!.intro=0;
    const battle=game.battle!;
    battle.foe.x=battle.ally.x;battle.foe.z=battle.ally.z;
    battle.ally.attackTimer=100;
    battle.foe.attackTimer=0;
    battle.foe.charge=100;
    game.update(0.02);
    expect(battle.foe.skillWindup).toBe(true);
    expect(battle.message).toContain('prepara');
    game.battleCommand('dodge');
    const hp=battle.ally.hp;
    for(let step=0;step<24;step++)game.update(0.05);
    expect(battle.ally.hp).toBe(hp);
    expect(battle.message).toBe('Esquivou!');
  });
  it('só aplica dano dentro da área anunciada e o inimigo descansa após atacar',()=>{
    const game=new Game();game.newGame('brasito',346);
    game.beginBattle(game.wildActors.find(w=>!w.night)!);
    game.battle!.intro=0;
    const battle=game.battle!;
    battle.command='move';battle.waypoint={x:battle.ally.x,z:battle.ally.z};
    battle.ally.attackTimer=100;
    battle.foe.attackTimer=100;
    battle.foe.windup=0.01;
    battle.foe.strikeOrigin={x:battle.foe.x,z:battle.foe.z};
    battle.foe.strikeRadius=1;
    const hp=battle.ally.hp;
    game.update(0.02);
    expect(battle.ally.hp).toBe(hp);
    expect(battle.foe.recovery).toBeGreaterThanOrEqual(1.2);
    battle.foe.windup=0.01;
    battle.foe.strikeOrigin={x:battle.ally.x,z:battle.ally.z};
    battle.foe.strikeRadius=1;
    battle.ally.dodgeTime=0.5;
    game.update(0.02);
    expect(battle.ally.hp).toBeLessThan(hp);
  });
  it('abre uma janela real para o aliado contra-atacar depois do golpe inimigo',()=>{
    const game=new Game();game.newGame('brasito',346);
    game.beginBattle(game.wildActors.find(w=>!w.night)!);
    game.battle!.intro=0;
    const battle=game.battle!;
    battle.enemy=createMonster('brotelho',1,'counter-window');
    battle.foe.hp=500;
    battle.ally.x=battle.foe.x;battle.ally.z=battle.foe.z;
    battle.command='attack';
    battle.ally.attackTimer=0;
    battle.foe.attackTimer=0;
    battle.foe.windup=0.01;
    battle.foe.strikeOrigin={x:battle.foe.x,z:battle.foe.z};
    battle.foe.strikeRadius=1.5;
    game.update(0.02);
    const health=battle.foe.hp;
    for(let step=0;step<12;step++)game.update(0.05);
    expect(battle.foe.hp).toBeLessThan(health);
    expect(battle.foe.recovery).toBeGreaterThan(0);
    expect(battle.foe.windup).toBeLessThanOrEqual(0);
  });
  it('voltar só interrompe a perseguição e conduz o companheiro para perto do herói',()=>{
    const game=new Game();game.newGame('brasito',346);
    const wild=game.wildActors.find(w=>!w.night)!;
    game.player.x=wild.x-1.3;game.player.z=wild.z-0.5;
    game.beginBattle(wild);game.battle!.intro=0;
    const battle=game.battle!;
    battle.ally.attackTimer=100;battle.foe.attackTimer=100;
    const initial=Math.hypot(battle.ally.x-game.player.x,battle.ally.z-game.player.z);
    game.battleCommand('return');
    expect(battle.command).toBe('return');
    game.battleCommand('follow');
    expect(battle.command).toBe('follow');
    game.battleCommand('return');
    for(let i=0;i<25;i++)game.update(0.05);
    expect(battle.command).toBe('return');
    expect(Math.hypot(battle.ally.x-game.player.x,battle.ally.z-game.player.z)).toBeLessThan(initial);
  });
  it('permite vencer um encontro selvagem perseguindo e esquivando',()=>{
    const game=new Game();game.newGame('brasito',346);
    game.beginBattle(game.wildActors.find(w=>!w.night)!);
    game.battle!.intro=0;
    game.battle!.enemy=createMonster('brotelho',1,'enemy');
    game.battle!.foe.hp=maxHp(game.battle!.enemy);
    game.battleCommand('follow');
    vi.spyOn(Math,'random').mockReturnValue(0.5);
    for(let step=0;step<1200&&game.mode==='battle';step++){
      if(game.battle!.foe.windup>0&&game.battle!.ally.dodgeCooldown===0)game.battleCommand('dodge');
      game.update(0.05);
    }
    expect(game.mode).toBe('explore');
    expect(game.save!.wins).toBe(1);
    expect(game.save!.party[0].hp).toBeGreaterThan(0);
  });
  it('faz uma investida por comando Atacar e volta a acompanhar o herói',()=>{
    for(const seed of [346,445,999]){
      const game=new Game();game.newGame('brasito',seed);
      const wild=game.wildActors.find(w=>!w.night)!;
      game.player.x=wild.x-1.3;game.player.z=wild.z-0.5;
      game.beginBattle(wild);
      const battle=game.battle!;
      battle.intro=0;
      battle.enemy=createMonster('brotelho',1,'enemy');
      battle.foe.hp=500;
      battle.foe.attackTimer=100;
      battle.foe.recovery=100;
      battle.ally.x=battle.foe.x;battle.ally.z=battle.foe.z;
      battle.ally.attackTimer=0;
      for(let step=0;step<20;step++)game.update(0.05);
      expect(battle.foe.hp).toBe(500);
      game.battleCommand('attack');
      battle.ally.x=battle.foe.x;battle.ally.z=battle.foe.z;
      for(let step=0;step<20;step++)game.update(0.05);
      expect(battle.command).toBe('return');
      const firstHit=battle.foe.hp;
      expect(firstHit).toBeLessThan(500);
      const beforeReturn=Math.hypot(battle.ally.x-game.player.x,battle.ally.z-game.player.z);
      for(let step=0;step<100;step++)game.update(0.05);
      expect(battle.foe.hp).toBe(firstHit);
      expect(Math.hypot(battle.ally.x-game.player.x,battle.ally.z-game.player.z)).toBeLessThan(beforeReturn);
      game.battleCommand('attack');
      battle.ally.x=battle.foe.x;battle.ally.z=battle.foe.z;
      battle.ally.attackTimer=0;
      for(let step=0;step<20;step++)game.update(0.05);
      expect(battle.foe.hp).toBeLessThan(firstHit);
    }
  });
  it('reserva a carga para o especial e mantém o ataque comum separado',()=>{
    const game=new Game();game.newGame('brasito',346);
    game.beginBattle(game.wildActors.find(w=>!w.night)!);
    const battle=game.battle!;
    battle.intro=0;
    battle.foe.hp=500;
    battle.foe.attackTimer=999;
    battle.ally.x=battle.foe.x;battle.ally.z=battle.foe.z;
    battle.ally.attackTimer=0;
    vi.spyOn(Math,'random').mockReturnValue(0.5);
    game.battleCommand('special');
    expect(battle.command).toBe('return');
    battle.ally.charge=100;
    game.battleCommand('attack');
    game.update(0.05);
    expect(battle.ally.skillWindup).toBe(false);
    expect(battle.ally.charge).toBe(100);
    for(let i=0;i<12;i++)game.update(0.05);
    expect(game.effects.some(effect=>effect.kind==='hit')).toBe(true);
    expect(battle.command).toBe('return');
    battle.ally.attackTimer=0;battle.ally.recovery=0;
    game.battleCommand('special');
    game.update(0.05);
    expect(battle.ally.skillWindup).toBe(true);
    expect(battle.ally.charge).toBeLessThan(1);
    for(let i=0;i<20;i++)game.update(0.05);
    expect(game.effects.some(effect=>effect.kind==='skill')).toBe(true);
    expect(battle.command).toBe('return');
  });
  it('consome uma carta também quando a captura falha e respeita o horário',()=>{
    const game=new Game();game.newGame('brasito',445);
    const nightWild=game.wildActors.find(w=>w.night)!;
    expect(game.isWildVisible(nightWild)).toBe(false);
    game.save!.elapsed=24*60*0.92;
    expect(game.isNight).toBe(true);
    expect(game.isWildVisible(nightWild)).toBe(true);
    game.beginBattle(nightWild);
    game.battle!.intro=0;
    const element=SPECIES[game.battle!.enemy.species].element;
    const cards=game.save!.cards[element];
    game.battle!.foe.hp=Math.floor(maxHp(game.battle!.enemy)*0.5);
    expect(game.captureChance()).toBeGreaterThanOrEqual(50);
    vi.spyOn(Math,'random').mockReturnValue(0.999);
    game.capture();
    expect(game.save!.cards[element]).toBe(cards-1);
    expect(game.mode).toBe('battle');
    expect(game.battle?.captureSequence?.success).toBe(false);
    const health=game.battle!.foe.hp;
    for(let step=0;step<Math.ceil(CAPTURE_FAIL_SECONDS/0.05)+2;step++)game.update(0.05);
    expect(game.battle?.captureSequence).toBeUndefined();
    expect(game.battle?.foe.hp).toBe(health);
    expect(game.mode).toBe('battle');
  });
  it('encerra a região com os três selos e mantém a exploração aberta',()=>{
    const game=new Game();game.newGame('brasito',777);
    for(const element of ['natureza','fogo','agua'] as const){
      const shrine=game.world!.places.find(place=>place.element===element)!;
      game.beginBattle(undefined,element,shrine);
      game.battle!.intro=0;
      const battle=game.battle!;
      battle.ally.x=battle.foe.x;battle.ally.z=battle.foe.z;
      battle.foe.hp=1;battle.ally.windup=0.001;
      battle.ally.strikeOrigin={x:battle.ally.x,z:battle.ally.z};battle.ally.strikeRadius=2;
      game.update(0.02);
      for(let step=0;step<Math.ceil(BATTLE_FINISH_SECONDS/0.05)+2&&game.mode==='battle';step++)game.update(0.05);
      expect(game.save!.seals).toContain(element);
    }
    expect(game.save!.completed).toBe(true);
    expect(game.save!.seals).toHaveLength(3);
    expect(game.mode).toBe('explore');
    expect(game.battle).toBeNull();
  });
});
